### ISSUE TITLE
Push notifications key names should correspond to GCM/APNs docs

### ISSUE THREAD

**Issue by jameshfisher** [pusher/pusher-http-go#28]
I don't understand why our naming scheme doesn't correspond to the names in the GCM/APNs request, e.g. "Payload" becomes "notification" https://github.com/pusher/pusher-http-go/blob/new-lib/notifications.go#L56 I think we want people to be able to refer to GCM/APNs docs to figure out what to send.

I'd also suggest just letting people pass a `map[string]interface{}` instead of our own internal representation of notifications. We do this in the other HTTP libs. The current method will mean constantly monitoring GCM/APNs for new features they add, and then including them here.

**Comment by jpatel531** [comment]
branch #24 and raise a PR :p

**Comment by jpatel531** [comment]
that's to say - i agree 👍
