### ISSUE TITLE
What about Receiving Pusher events

### ISSUE THREAD

**Issue by maded2** [pusher/pusher-http-go#4]
hi,
  I also like to be able to receive pusher events in my golang app (ie. just like the Browser client).  Is that possible with this lib?

thanks,
eddie

**Comment by zimbatm** [comment]
Hi, this library is only for interacting with the HTTP API. You are thinking of the `pusher-websocket-go` library which unfortunately hasn't been written yet.

**Comment by jpatel531** [comment]
Hi there @maded2 - I have been working on a websocket Pusher client for Go, however it is far from being ready to release :p 

I'm just curious - what kinds of applications would you use with such a library? This is so I know what to have in mind for working on it in the future

**Comment by maded2** [comment]
some of the realtime data providers my app connects to uses Pusher to deliver data (mainly for Web UI).  But I also need to capture the pusher data stream into my Go server backend for processing and storing to a database.  I could use NodeJs running your Javascript client, but its not a good solution; preferred using Go as part of my server backend.

**Comment by jpatel531** [comment]
fair enough! thanks for the info - i'll keep it in mind :)

**Comment by rgbkrk** [comment]
In my case, I want to provide a Go binary to users that can send events to pusher (note that I'm still evaluating options here) which of course means I don't want to ship with my key embedded in the app.

**Comment by zimbatm** [comment]
@maded2 I recommend that you use the webhooks. WebSocket would work but you might miss some data if your server gets disconnected. HTTP is also easier to scale horizontally.

@rgbkrk are users going to be authenticated against your service ? Each request is signed and signature generation could be delegated to your service. The go lib doesn't support it right now but it wouldn't be too hard to add a custom authenticator.

**Comment by rgbkrk** [comment]
@zimbatm At the moment, no. This is for a demo/lightning talk I'll do at PyData Seattle, hoping to rely on an external service + a static page.

**Comment by zimbatm** [comment]
@rgbkrk I recommend you do something like that:  go client --(http)--> go server --(http)--> pusher server. Then you can build the auth that you want between your client and server. If you don't want to host a server then the only way is to bundle the pusher key/pair. You can always change them if there is too much abuse or want to commercialize your hack.

**Comment by jpatel531** [comment]
We've open sourced pusher-websocket-go on the community organization. https://github.com/pusher-community/pusher-websocket-go

Note that it's far from production-ready. There's no tests, particularly for the re-connection logic. But do feel free to play around with it and raise any issues you encounter
