### ISSUE TITLE
Introducing Breaking Changes

### ISSUE THREAD

**Issue by Fyb3roptik** [pusher/pusher-http-go#57]
You changed AppId to AppID and also UserId to UserID and it took me hours to figure out why my deployments weren't working. Come on guys lets not introduce breaking changes like this without some sort of heads up!

**Comment by kn100** [comment]
Hey,

Sorry for the trouble. We make use of Semver in this library and will increment the major version number whenever API breaking changes are introduced, as here. There were a number of style problems in this Library which I needed to address, which is where this change comes from. There have been a few other changes, which you can read about in the changelog in the root of the repo, or on the releases page, here: https://github.com/pusher/pusher-http-go/releases.

It's a good idea to give this changelog a read before upgrading any major versions, as they'll almost certainly require work on your end to upgrade.

Is there anything else we could do?

**Comment by Fyb3roptik** [comment]
Well AFAIK Go doesn't provide a way to specify a version for Docker. I use docker for production and it just installs the latest. Took down our production for a few hours until I could pinpoint the issue.

**Comment by kn100** [comment]
I'm sincerely sorry for that - it was obviously never my intention to cause trouble for you like this. There are no breaking changes coming for a while on this library from here on, and I'm going to bring this up with my team to discuss better ways of notifying consumers of our libraries that they're coming. Do you have any specific suggestions on how best to notify you about these sorts of breaking changes? We're definitely listening and eager to make sure we annoy as few people as possible.

**Comment by Fyb3roptik** [comment]
Its all good, I know why you did it and I wish Go had better dependency management. I am probably going to have to start using The Athens Project for this

**Comment by kn100** [comment]
Closed, and feedback truly taken on board. Thanks for taking the time!
