### ISSUE TITLE
timeouts

### ISSUE THREAD

**Issue by jney** [pusher/pusher-http-go#58]
Hello,
I've got the following quite often:

```
request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

Where timeout could come from?

thank you

**Comment by kn100** [comment]
Hi,
I've got a couple questions to help me get to the bottom of this:
Have you manually configured timeout values anywhere in your codebase?
Is it always the same kind of request failing? It might make sense to add code to log failed payloads.
What percentage of requests are failing?
Which cluster are you using?
What's your request rate?
Where are your servers located in the world?
Are you running the latest version of the library? (mind the breaking changes! see the release log here: https://github.com/pusher/pusher-http-go/releases)

**Comment by jney** [comment]
Hi @kn100 I think the problem was actually on my side, pusher was called in a goroutine, and I wasn't waiting to be done. solved using some `WaitGroup`.
Anyway thank you for the support

**Comment by kn100** [comment]
You're more than welcome! Goroutines are fun.
