### ISSUE TITLE
Current design doesn't allow switching the http client

### ISSUE THREAD

**Issue by wingedkiwi** [pusher/pusher-http-go#6]
Some environments doesn't support the default http client (like Google App Engine).
Current design makes it difficult to switch out the http client.

The workaround is currently to switch only the underlying transport if this is enough by:
`
client.HttpClient().Transport = urlfetch.Client(c).Transport
`

This is related to: https://github.com/pusher/pusher-http-go/issues/5

**Comment by jpatel531** [comment]
Good points! I'm on it :)

**Comment by jpatel531** [comment]
The [gae branch](https://github.com/pusher/pusher-http-go/tree/gae) has been tested out with app engine - and takes on the points you mentioned. WDYT? :)

**Comment by jpatel531** [comment]
Closed for now - feel free to reopen :)

**Comment by wingedkiwi** [comment]
Thanks! Looks good!
