### ISSUE TITLE
No easily mockable

### ISSUE THREAD

**Issue by spartan218** [pusher/pusher-http-go#63]
I am currently working with this library and wanted to add it to my tests.
Unfortunately because there is no interface the only way to test this client is to 
actually hook into a real pusher client.

Would it be reasonable to add an interface definition to the Client or at the very least
provide a NoOp client that returns common calls such as `Trigger()` with no errors?

I am open to suggestions as well in case I have an oversight.

Also, not just gonna request, but happy to try and contribute to this if it seems like a reasonable idea.

**Comment by mrsufgi** [comment]
Well I guess until they officially release that Interface, you can (and probably did) created your own Interface and used it internally and than mocked it :O
