### ISSUE TITLE
pusherClient.SendToUser

### ISSUE THREAD

**Issue by fcastillo90** [pusher/pusher-http-go#86]
How can i push to a specific user in Go? The documentation states that I should use `pusherClient.SendToUser` but get this error instead:

`pusherClient.SendToUser undefined (type pusher.Client has no field or method SendToUser)`

**Comment by benw-pusher** [comment]
You will need to ensure you are using the correct version - version 5.1.0 introduces  `SendToUser` https://github.com/pusher/pusher-http-go/blob/master/CHANGELOG.md#510
