### ISSUE TITLE
Auth value for subscription to private-chat-room is invalid

### ISSUE THREAD

**Issue by NicholasPmiranda** [pusher/pusher-http-go#88]
hello I'm facing a problem when trying to access a private channel

I created the same authentication route as in the documentation example

```
	app.Post("pusher/auth", func(c *fiber.Ctx) error {
		
		var pusherClient pusher.Client
		response, err := pusherClient.AuthorizePrivateChannel(c.Body())

		if err != nil {
			fmt.Println(err)
		}

		return c.JSON(fiber.Map{"auth": response})
	})
```

it returns the token correctly but when it returns the following error

send token
```
{"event":"pusher:subscribe","data":{"auth":"eyJhdXRoIjoiOjJlMTcxYjJmZTc3ZDE0NjQ1ZTMyMzQzNGQ1YWFiMjhiZWVlMmYzYmI4OGJmMTdhNzU4YmRjODYxZWI0NGI3NzUifQ==","channel":"private-chat-room"}}
```
error code

```
{"event":"pusher:error","data":{"code":null,"message":"Auth value for subscription to private-chat-room is invalid: should be of format 'key:signature'"}}
```

it asks for a token with the pre-fixed app-key: but I couldn't contact it because the token comes in a byte slice type

**Comment by benw-pusher** [comment]
As you have mentioned, the app-key needs to be prefixed to the token. When using the go library this should happen automatically, as long as the key is provided when the client is instantiated. Can you confirm your Pusher instance, as described at https://github.com/pusher/pusher-http-go#configuration, has the correct id, key, secret and cluster provided when instantiated?

**Comment by NicholasPmiranda** [comment]
yes I informed the app key but the app key is not returned
```
package websocket

import (
	"fmt"
	"github.com/gofiber/fiber/v2"
	"github.com/pusher/pusher-http-go/v5"
	"time"
)

var (
	PusherClient pusher.Client
)

func PusherConnect() pusher.Client {
	PusherClient = pusher.Client{
		AppID:   "1235123721",
		Key:     "b38c5e123e14d02be23ca696d",
		Secret:  "e1641cc5123813c23461b6ade",
		Cluster: "us2",
		Secure:  true,
	}

	return PusherClient
}

func PusherAuth(c *fiber.Ctx) error {
	var pusherClient pusher.Client
	response, err := pusherClient.AuthorizePrivateChannel(c.Body())

	if err != nil {
		fmt.Println(err)
	}

	return c.JSON(fiber.Map{"auth": response})
}
```

in this case, the Pusher Connect function is called in the main.go file where the application is started and it is the auth function when authentication is requested

**Comment by benw-pusher** [comment]
The auth function appears to be using a local scope pusher.Client with no credentials set - `var pusherClient pusher.Client
`. You should ensure you are re-using the instance from the PusherConnect function, or using a new instance with credentials passed.

**Comment by NicholasPmiranda** [comment]
> The auth function appears to be using a local scope pusher.Client with no credentials set - `var pusherClient pusher.Client `. You should ensure you are re-using the instance from the PusherConnect function, or using a new instance with credentials passed.

I put all the connection data in the same method but I had the same return

```
func PusherAuth(c *fiber.Ctx) error {
	PusherClient := pusher.Client{
		AppID:   "1231235721",
		Key:     "b38c5ee14asdd02beca696d",
		Secret:  "e1641cc58qwe13c461b6ade",
		Cluster: "us2",
		Secure:  true,
	}

	response, err := PusherClient.AuthorizePrivateChannel(c.Body())

	if err != nil {
		fmt.Println(err)
	}

	return c.JSON(fiber.Map{"auth": response})
}
```

**Comment by benw-pusher** [comment]
I've run up a simple test script and it correctly prepends the key to the token. I haven't been able to replicate a scenario where the key isn't prepended

```
    pusherClient := pusher.Client{
        AppID:   "1234",
        Key:     "aae11111111111111111",
        Secret:  "aae22222222222222222",
        Cluster: "eu",
    }
    
postParams := []byte("channel_name=private-foobar&socket_id=1234.1234")
	response, err := pusherClient.AuthorizePrivateChannel(postParams)
	fmt.Printf(string(response))
```

which outputs: 
```
{"auth":"aae11111111111111111:23759e166a7cfbfe4d9c70e4e3b920aa4eed643006e0731fb985de27123db66c"}%   
```

If you log the response before sending it with `return c.JSON(fiber.Map{"auth": response})` does it appear correct? I wonder if the issue is with the JSON/fiber.Map operation.

**Comment by benw-pusher** [comment]
We haven't had a response here so it is likely you have moved on - if that is not the case please let us know via https://support.pusher.com/hc/en-us/requests/new and we can progress with you.

**Comment by vessenes** [comment]
FWIW, I just experienced this today. And, as you suggested, the reason I got the error was that I was using a Pusher client instantiated with no variables, like KEY, APP ID, etc. 

I'll put in that it's a surprise to me that I got no warning or error from the module when I instantiated it this way -- it just cheerfully is like "Yep, I'm talking to Pusher". I'd suggest it returns an error.
