### ISSUE TITLE
"Trigger()" function returning error on deployed backend  - "Invalid signature: you should have sent HmacSHA256Hex"

### ISSUE THREAD

**Issue by darienmiller88** [pusher/pusher-http-go#91]
I have a basic go backend deployed on fly.io that serves a POST route that takes a Message, and calls the Trigger function, which would get picked up by my front end and displayed on the screen. During local development, this workflow works perfectly, but calling the POST route on the api at the deployed URL produces the following error:

`
Status Code: 401 - Invalid signature: you should have sent HmacSHA256Hex("POST\n/apps/PUSHER_APPID/events\nauth_key=PUSHER_KEY&auth_timestamp=1701978133&auth_version=1.0&body_md5=5c97a1d17397906fcfbfb622622a2b59", your_secret_key), but you sent "e2abd797832ba0fe963c77dd2656aae135a2bd2e45afc9d419ac3a7e2ae59765"
`

```
func (m *MessageController) PostMessage(c *fiber.Ctx) error{
	message := models.Message{}

	if err := c.BodyParser(&message); err != nil{
		c.Smetatus(http.StatusInternalServerError).JSON(err)
	}

	if err := message.Validate(); err != nil{
		c.Status(http.StatusBadRequest).JSON(err)
	}

	message.MessageDate = time.Now().Format("2006-01-02 3:4:5 pm")
	err := m.pusherClient.Trigger("public", "public_message", message)

	if err != nil{
		fmt.Println("err broadcasting messages:", err) //Error is thrown right here, and message is not broadcasted.
	}
	
	return c.Status(http.StatusOK).JSON(message)
}
```

What's causing this error? It only happens when calling the route on the deployed API, but when calling the same route locally, the message is broadcasted normally, and the error is not thrown.

**Comment by benw-pusher** [comment]
Are you using the same Pusher app for your deployed API and the local deployment? Often this is a result of a mismatch of app ID and keys / secrets, which can happen when env vars are not updated or set correctly when switching environment. IT would be worth double checking the values for these are correct and match the correct app.

**Comment by darienmiller88** [comment]
Hello,

Yes, this appeared to have been the case. On my deployed backend, I forgot to set the PUSHER_SECRET env variable. This solved the problem I was having. Thanks!
